spring.application.name=reporting-service


server.port=8086

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
sspring.datasource.username=system
spring.datasource.password=briju123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true
spring.jpa.properties.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.format_sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration-ms=900000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always